default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: restaurants_development

test:
  <<: *default
  database: restaurants_test

production:
  <<: *default
  database: restaurants_production
